apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
      app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-0
  namespace: default
  labels:
      app: redis
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "redis-0"
spec:
  ports:
      - port: 6379
        name: redis
  selector:
      app: redis
      statefulset.kubernetes.io/pod-name: redis-0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: default
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: ghcr.io/dzfranklin/my-redis-infra:2
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /redis-data
